// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIAKtn635YXn9W7uwOKLxyqBhMNHMonS0',
    appId: '1:555759143065:web:1cec18e9f948563c8a9008',
    messagingSenderId: '555759143065',
    projectId: 'voyage-91316',
    authDomain: 'voyage-91316.firebaseapp.com',
    storageBucket: 'voyage-91316.appspot.com',
    measurementId: 'G-T8BRQWP4VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5yV5yUNj505TnclkL8Wmwz4o9HMGgkk',
    appId: '1:555759143065:android:53b3d0b3e4c0961d8a9008',
    messagingSenderId: '555759143065',
    projectId: 'voyage-91316',
    storageBucket: 'voyage-91316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBvlZFOJLMDOe4BfputT6lN5rYeb7rjc',
    appId: '1:555759143065:ios:c4ba09fdaf9b310a8a9008',
    messagingSenderId: '555759143065',
    projectId: 'voyage-91316',
    storageBucket: 'voyage-91316.appspot.com',
    iosBundleId: 'com.example.voyage',
  );
}
